# Generated by Django 6.0.1 on 2026-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='avg_feedback_score',
            field=models.FloatField(default=0),
        ),
    ]
