# Generated by Django 6.0.1 on 2026-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisresult_avg_feedback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='weather_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='windspeed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
