# Generated by Django 5.0.6 on 2026-01-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisresult_temperature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Analysis Results'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='ai_score',
            field=models.IntegerField(help_text='0-100 overall livability score'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='ai_summary',
            field=models.TextField(help_text='AI-generated summary'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='avg_feedback_score',
            field=models.FloatField(default=0, help_text='Average score from user feedback (0-5)'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis.location'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='noise_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='rent_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='safety_score',
            field=models.FloatField(help_text='0-10 safety rating'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Apparent temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='water_quality',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='weather_code',
            field=models.CharField(blank=True, help_text='Weather risk level', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='windspeed',
            field=models.FloatField(blank=True, help_text='Wind speed in km/h', null=True),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['user', '-created_at'], name='analysis_an_user_id_cfe621_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['location', '-created_at'], name='analysis_an_locatio_000d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='analysis_lo_latitud_be925b_idx'),
        ),
    ]
