# Generated by Django 5.0.6 on 2026-01-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_score', models.IntegerField()),
                ('noise_level', models.IntegerField()),
                ('rent_index', models.IntegerField()),
                ('water_quality', models.IntegerField()),
                ('population_density', models.IntegerField()),
                ('ai_score', models.IntegerField()),
                ('summary', models.TextField()),
                ('raw_ai_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisresult')),
            ],
        ),
    ]
