# Generated by Django 5.0.6 on 2026-01-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysisresult_options_alter_location_options_and_more'),
        ('reports', '0002_reportanalytics_delete_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportanalytics',
            options={'verbose_name_plural': 'Report Analytics'},
        ),
        migrations.AlterField(
            model_name='reportanalytics',
            name='feedback_score',
            field=models.IntegerField(blank=True, help_text='Average user feedback score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='reportanalytics',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='analysis.analysisresult'),
        ),
        migrations.AlterField(
            model_name='reportanalytics',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this report has been viewed'),
        ),
    ]
