# Generated by Django 5.0.6 on 2026-01-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysisresult_options_alter_location_options_and_more'),
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfeedback',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Report Feedback'},
        ),
        migrations.AlterField(
            model_name='reportfeedback',
            name='accuracy',
            field=models.IntegerField(help_text='1-5 rating for accuracy'),
        ),
        migrations.AlterField(
            model_name='reportfeedback',
            name='clarity',
            field=models.IntegerField(help_text='1-5 rating for clarity'),
        ),
        migrations.AlterField(
            model_name='reportfeedback',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional additional comments'),
        ),
        migrations.AlterField(
            model_name='reportfeedback',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='analysis.analysisresult'),
        ),
        migrations.AlterField(
            model_name='reportfeedback',
            name='usefulness',
            field=models.IntegerField(help_text='1-5 rating for usefulness'),
        ),
        migrations.AlterField(
            model_name='reportfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportfeedback',
            unique_together={('report', 'user')},
        ),
        migrations.AddIndex(
            model_name='reportfeedback',
            index=models.Index(fields=['report', '-created_at'], name='community_r_report__d2ed70_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfeedback',
            index=models.Index(fields=['user', '-created_at'], name='community_r_user_id_0dfa7e_idx'),
        ),
    ]
